testing zip

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -33,18 +33,21 @@ pipelines:
             - cd cypress
             - npm ci
             # Run Cypress tests in headless mode
-            - npm run cy:alltests --browser chrome
+            - npm run cy:alltests --browser chrome || true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
+            - ls -al
             # - npm run cy:permissions --browser chrome
-            - apt-get update && apt-get install -y zip jq tree
-            - ls -al cypress/
-            - zip -r reports.zip cypress/reports/
-            - tree -I "node_modules"
           after-script:
             - cd cypress-tests/cypress
+            - apt-get update && apt-get install -y zip jq tree
+            - zip -r reports.zip cypress/reports/
+            - tree -I "node_modules"
             - ls -al
             - zip -r reports.zip cypress/reports/
             - ALERT_TYPE="success"
-            - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then ALERT_TYPE="error" ; fi
+            - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then 
+                ALERT_TYPE="error";
+                echo "Tests failed but continuing with report generation";
+              fi
             - echo "$SMTP_USERNAME"
             - echo "$SMTP_PASSWORD"
             - pipe: atlassian/email-notify:0.13.2
@@ -52,7 +55,7 @@ pipelines:
                 USERNAME: $SMTP_USERNAME
                 PASSWORD: $SMTP_PASSWORD
                 FROM: 'seguetesting@gmail.com'
-                TO: 'testing@segue360.co.uk'
+                TO: 'asara97911@gmail.com'
                 HOST: 'smtp.gmail.com'
                 PORT: 465
                 SUBJECT: '${ALERT_TYPE}:Bitbucket Pipe Notification for ${BITBUCKET_BRANCH}'
